const D=window.ND6_DATA, $=s=>document.querySelector(s), esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const K='nd6.'; const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(K+k))??d}catch{return d}}, set=(k,v)=>localStorage.setItem(K+k,JSON.stringify(v));
let view='home', calCursor=new Date(); const me=()=>get('profile',{id:'',name:''});
function toast(x){let e=document.createElement('div');e.className='toast';e.textContent=x;document.body.append(e);setTimeout(()=>e.remove(),1800)}
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function ensureProfile(){let p=me(); if(!p.id){p={id:uuid(),name:''};set('profile',p)} return p}
function fmt(dt){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(dt))}

function opts(from,to,val,pad=true){let h='';for(let i=from;i<=to;i++){let v=pad?String(i).padStart(2,'0'):String(i);h+=`<option value="${v}" ${String(val)===v?'selected':''}>${v}</option>`}return h}
function dateParts(value,withTime=false){let d=value?new Date(value):new Date(), y=d.getFullYear(),mo=String(d.getMonth()+1).padStart(2,'0'),da=String(d.getDate()).padStart(2,'0'),h=String(d.getHours()).padStart(2,'0'),mi=String(d.getMinutes()).padStart(2,'0');return {y:String(y),mo,da,h,mi}}
function dateSelectors(prefix,value,withTime=false){let x=dateParts(value,withTime),years=opts(new Date().getFullYear()-1,new Date().getFullYear()+10,x.y,false);return `<div class="datepick"><select id="${prefix}d" aria-label="Jour">${opts(1,31,x.da)}</select><select id="${prefix}m" aria-label="Mois">${opts(1,12,x.mo)}</select><select id="${prefix}y" aria-label="Année">${years}</select>${withTime?`<select id="${prefix}h" aria-label="Heure">${opts(0,23,x.h)}</select><span>:</span><select id="${prefix}i" aria-label="Minute">${opts(0,59,x.mi)}</select>`:''}</div>`}
function readDate(prefix,withTime=false){let y=$('#'+prefix+'y').value,m=$('#'+prefix+'m').value,d=$('#'+prefix+'d').value;let max=new Date(Number(y),Number(m),0).getDate();if(Number(d)>max)d=String(max).padStart(2,'0');return `${y}-${m}-${d}`+(withTime?`T${$('#'+prefix+'h').value}:${$('#'+prefix+'i').value}`:'')}
function countdown(){let x=get('reunion','');if(!x)return 'Date à définir';let ms=new Date(x)-Date.now();if(ms<=0)return '❤️ Vous êtes réunis';let d=Math.floor(ms/864e5);ms%=864e5;let h=Math.floor(ms/36e5);ms%=36e5;let m=Math.floor(ms/6e4);return `J-${d} • ${h} h • ${m} min`}
function render(){ensureProfile();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===view));let a=$('#app'); if(view==='home')home(a);if(view==='questions')qa(a,'questions');if(view==='challenges')qa(a,'challenges');if(view==='calendar')calendar(a);if(view==='sync')sync(a);if(view==='pair')pair(a);if(view==='spaces')spaces(a)}
function home(a){let p=me(),msgs=get('messages',[]),rv=get('reunion','');a.innerHTML=`<section class=hero><div>❤️</div><h1>Nous Deux</h1><p class=muted>${esc(p.name||'Configure ton prénom')}</p><div class=count>${countdown()}</div><p class=muted>avant vos retrouvailles</p></section><div class=card><h3>⏱️ Prochaines retrouvailles</h3><label>Jour / mois / année / heure / minute</label>${dateSelectors('r',rv,true)}<button class=action id=saveReunion>Enregistrer</button></div><div class=card><h3>💌 Messages</h3><textarea id=msg placeholder="Un petit mot pour l'autre…"></textarea><button class=action id=sendMsg>Ajouter au journal partagé</button>${msgs.slice(-5).reverse().map(m=>`<div class=event><b>${esc(m.authorName)}</b> <span class=status>${fmt(m.at)}</span><br>${esc(m.text)} <button class=ghost data-delmsg="${m.id}">Supprimer</button></div>`).join('')}</div><div class=grid><button class="ghost spacebtn" id=openSpaces>🔒 Espaces à deux</button><button class="ghost spacebtn" onclick="view='calendar';render()">🗓️ Nos week-ends</button></div>`;$('#saveReunion').onclick=()=>{set('reunion',readDate('r',true));toast('Retrouvailles enregistrées');render()};$('#sendMsg').onclick=()=>{let t=$('#msg').value.trim();if(!t)return;let p=me(),x=get('messages',[]);x.push({id:uuid(),authorId:p.id,authorName:p.name||'Moi',text:t,at:new Date().toISOString()});set('messages',x);render()};a.querySelectorAll('[data-delmsg]').forEach(b=>b.onclick=()=>{let id=b.dataset.delmsg;set('messages',get('messages',[]).filter(m=>m.id!==id));let del=get('deletedMessages',[]);if(!del.includes(id))del.push(id);set('deletedMessages',del);toast('Message supprimé');render()});$('#openSpaces').onclick=()=>{view='spaces';render()}}
function answerText(v){if(v==null)return '';if(typeof v==='object')return typeof v.text==='string'?v.text:'';return String(v)==='[object Object]'?'':String(v)}
function migrateBrokenAnswers(){let a=get('answers',{}),changed=false;for(const users of Object.values(a)){if(!users||typeof users!=='object')continue;for(const [uid,v] of Object.entries(users)){if(v==='[object Object]'){delete users[uid];changed=true}else if(v&&typeof v==='object'&&v.text==='[object Object]'){v.text='';changed=true}}}if(changed)set('answers',a);return changed}
function qa(a,type){let list=D[type], title=type==='questions'?'Questions':'Défis', themes=[...new Set(list.map(x=>x.theme))], pref=get(type+'Theme','Tous');let adult=get('adult',false);let filtered=list.filter(x=>(pref==='Tous'||x.theme===pref)&&(type!=='challenges'||adult||x.theme!=='Coquin'));let idx=get(type+'Idx',0)%filtered.length,item=filtered[idx],ans=get('answers',{}),p=me(),mineRaw=(ans[item.id]||{})[p.id]||'',mine=answerText(mineRaw);let others=Object.entries(ans[item.id]||{}).filter(([id])=>id!==p.id);let mineSaved=mine?`<div class=answer><b>Moi — réponse enregistrée</b><p>${esc(mine)}</p></div>`:'<p class=muted>Aucune réponse enregistrée pour moi.</p>';a.innerHTML=`<h2>${type==='questions'?'❓':'✨'} ${title}</h2><div class=tabs>${['Tous',...themes.filter(t=>adult||t!=='Coquin')].map(t=>`<button class="${t===pref?'btn':'ghost'}" data-theme="${esc(t)}">${esc(t)}</button>`).join('')}</div>${type==='challenges'?`<div class=card><label><input id=adult type=checkbox ${adult?'checked':''} style="width:auto"> Activer la catégorie « Coquin » (suggestive, optionnelle)</label></div>`:''}<div class=card><span class=pill>${esc(item.theme)}</span><h3>${esc(item.text)}</h3><label>Ma réponse / mon retour</label><textarea id=ans>${esc(mine)}</textarea><button class=action id=saveAns>Enregistrer ma réponse</button><button class=ghost id=next style="margin-left:6px">Suivant</button></div><div class=card><h3>📝 Ma réponse enregistrée</h3>${mineSaved}</div><div class=card><h3>❤️ Réponse du/de la partenaire</h3>${others.length?others.map(([id,r])=>`<div class=answer><b>${esc((r&&typeof r==='object'&&r.name)||'Partenaire')}</b><p>${esc(answerText(r))}</p></div>`).join(''):'<p class=muted>En attente de la réponse de ton/ta partenaire.</p>'}</div><p class=muted>${idx+1} / ${filtered.length} dans cette sélection • ${list.length} ${title.toLowerCase()} au total</p>`;a.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{set(type+'Theme',b.dataset.theme);set(type+'Idx',0);render()});if($('#adult'))$('#adult').onchange=e=>{set('adult',e.target.checked);render()};$('#saveAns').onclick=()=>{let t=$('#ans').value;if(t==='[object Object]')t='';let all=get('answers',{});all[item.id]=all[item.id]||{};all[item.id][p.id]={name:p.name||'Moi',text:t,at:new Date().toISOString()};set('answers',all);toast('Réponse enregistrée');render()};$('#next').onclick=()=>{set(type+'Idx',idx+1);render()}}

function calendar(a){let y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()+1),events=get('events',[]),days=[];for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`, has=events.some(e=>iso>=e.start&&iso<=e.end);days.push(`<div class="day ${d.getMonth()!==m?'off':''} ${iso===new Date().toISOString().slice(0,10)?'today':''} ${has?'has':''}" data-date="${iso}">${d.getDate()}</div>`)}a.innerHTML=`<div class=calendar-head><button class=ghost id=prev>‹</button><h2>${new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(first)}</h2><button class=ghost id=nextm>›</button></div><div class=cal>${['L','M','M','J','V','S','D'].map(x=>`<div class=dow>${x}</div>`).join('')}${days.join('')}</div><div class=card><h3>➕ Date / week-end</h3><input id=et placeholder="Titre"><label>Du</label>${dateSelectors('s','',false)}<label>Au</label>${dateSelectors('e','',false)}<textarea id=en placeholder="Note (facultatif)"></textarea><button class=action id=addEvent>Ajouter</button></div><div class=card><h3>Événements</h3>${events.slice().sort((x,y)=>x.start.localeCompare(y.start)).map(e=>`<div class=event><b>${esc(e.title)}</b><br><span class=status>${e.start}${e.end!==e.start?' → '+e.end:''}</span><br>${esc(e.note||'')} <button class=ghost data-del="${e.id}">Supprimer</button></div>`).join('')||'<p class=muted>Aucun événement.</p>'}</div>`;$('#prev').onclick=()=>{calCursor=new Date(y,m-1,1);render()};$('#nextm').onclick=()=>{calCursor=new Date(y,m+1,1);render()};a.querySelectorAll('.day[data-date]').forEach(el=>el.onclick=()=>{let z=el.dataset.date.split('-');['s','e'].forEach(p=>{$('#'+p+'y').value=z[0];$('#'+p+'m').value=z[1];$('#'+p+'d').value=z[2]});toast('Date sélectionnée : '+z.reverse().join('/'))});$('#addEvent').onclick=()=>{let s=readDate('s'),e=readDate('e'),t=$('#et').value.trim();if(!t)return toast('Titre requis');if(e<s)return toast('La date de fin doit être après le début');let x=get('events',[]);x.push({id:uuid(),title:t,start:s,end:e,note:$('#en').value,authorId:me().id});set('events',x);render()};a.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{set('events',get('events',[]).filter(e=>e.id!==b.dataset.del));render()})}
function spaces(a){let cards=get('spaceCards',[]);a.innerHTML=`<h2>🔒 Espaces à deux</h2><p class=muted>Crée une note secrète, prépare-la à envoyer, ou partage-la avec ton/ta partenaire.</p>${Object.entries(D.spaces).map(([s,rs])=>`<div class=card><h3>${esc(s)}</h3>${rs.map(r=>`<button class="ghost spacebtn" data-r="${esc(s+' • '+r)}">${esc(r)}</button>`).join('')}</div>`).join('')}<div class=card><h3>Contenus</h3>${cards.slice().reverse().map(c=>`<div class=event><span class=pill>${c.state==='secret'?'🔒 Secret':c.state==='send'?'💌 À envoyer':'❤️ Commun'}</span><b>${esc(c.rubric)}</b><p>${esc(c.text)}</p><small>${esc(c.authorName)}</small></div>`).join('')||'<p class=muted>Aucun contenu.</p>'}</div>`;a.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{let text=prompt(b.dataset.r+'\n\nTon contenu :');if(!text)return;let st=prompt('État : secret / send / shared','send');if(!['secret','send','shared'].includes(st))st='send';let p=me(),x=get('spaceCards',[]);x.push({id:uuid(),rubric:b.dataset.r,text,state:st,authorId:p.id,authorName:p.name||'Moi',at:new Date().toISOString()});set('spaceCards',x);render()})}
const B64='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
function bytesToB64(bytes){let out='',i=0;for(;i+2<bytes.length;i+=3){let n=(bytes[i]<<16)|(bytes[i+1]<<8)|bytes[i+2];out+=B64[(n>>18)&63]+B64[(n>>12)&63]+B64[(n>>6)&63]+B64[n&63]}let r=bytes.length-i;if(r===1){let n=bytes[i]<<16;out+=B64[(n>>18)&63]+B64[(n>>12)&63]+'=='}else if(r===2){let n=(bytes[i]<<16)|(bytes[i+1]<<8);out+=B64[(n>>18)&63]+B64[(n>>12)&63]+B64[(n>>6)&63]+'='}return out}
function b64ToBytes(str){str=(str||'').normalize('NFKC').replace(/[\s\u200B-\u200D\u2060\uFEFF]/g,'').replace(/-/g,'+').replace(/_/g,'/').replace(/[^A-Za-z0-9+/=]/g,'');str=str.replace(/=+$/,'');let out=[],buf=0,bits=0;for(const ch of str){let v=B64.indexOf(ch);if(v<0)continue;buf=(buf<<6)|v;bits+=6;if(bits>=8){bits-=8;out.push((buf>>bits)&255);buf&=(1<<bits)-1}}return new Uint8Array(out)}
function b64u(bytes){return bytesToB64(bytes).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){let out=b64ToBytes(s);if(!out.length&&String(s||'').trim())throw Error('Décodage Base64URL impossible');return out}
async function gzipBytes(bytes){if(!('CompressionStream'in window))return {kind:'J',bytes};let cs=new CompressionStream('gzip'),w=cs.writable.getWriter();await w.write(bytes);await w.close();return {kind:'Z',bytes:new Uint8Array(await new Response(cs.readable).arrayBuffer())}}
async function gunzipBytes(bytes,kind){if(kind!=='Z')return bytes;if(!('DecompressionStream'in window))throw Error('Décompression non disponible sur cet appareil');let ds=new DecompressionStream('gzip'),w=ds.writable.getWriter();await w.write(bytes);await w.close();return new Uint8Array(await new Response(ds.readable).arrayBuffer())}
async function fp(raw){let h=new Uint8Array(await crypto.subtle.digest('SHA-256',raw));return [...h.slice(0,12)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase().match(/.{1,4}/g).join(' · ')}
async function pair(a){let key=get('key',''),p=me();a.innerHTML=`<h2>🔐 Appairage V6</h2><div class=card><label>Ton prénom / pseudo sur cet appareil</label><input id=name value="${esc(p.name)}"><button class=action id=saveName>Enregistrer</button></div><div class=card><h3>Clé du couple</h3><p class=muted>Une même clé sur vos deux téléphones, deux identités d'appareil distinctes.</p><textarea id=key placeholder="Clé Base64URL">${esc(key)}</textarea><button class=action id=createKey>Créer une clé</button> <button class=ghost id=importKey>Importer</button><p id=fingerprint class=status></p></div>`;$('#saveName').onclick=()=>{p.name=$('#name').value.trim();set('profile',p);toast('Profil enregistré')};$('#createKey').onclick=async()=>{let raw=crypto.getRandomValues(new Uint8Array(32)),k=b64u(raw);set('key',k);$('#key').value=k;$('#fingerprint').textContent='Empreinte : '+await fp(raw)};$('#importKey').onclick=async()=>{try{let raw=unb64u($('#key').value.trim());if(raw.length!==32)throw 0;set('key',b64u(raw));$('#fingerprint').textContent='Empreinte : '+await fp(raw);toast('Clé importée')}catch{toast('Clé invalide')}};if(key){try{$('#fingerprint').textContent='Empreinte : '+await fp(unb64u(key))}catch{}}}
function changedAfter(x,cut){if(!cut)return true;let t=x?.at||x?.updatedAt||'';return !t||t>cut}
function exportData(mode='delta'){let p=me(),cards=get('spaceCards',[]).filter(c=>c.state!=='secret'),cut=mode==='delta'?get('peerAckAt',''):'';let answers=get('answers',{}),outAns={};for(const [qid,users] of Object.entries(answers)){for(const [uid,r] of Object.entries(users||{})){if(!cut||typeof r!=='object'||!r.at||r.at>cut){outAns[qid]=outAns[qid]||{};outAns[qid][uid]=r}}}let now=new Date().toISOString();return {v:6,rev:'6.5',mode,packetAt:now,ackFor:get('lastReceivedPacketAt',''),from:{id:p.id,name:p.name},reunion:get('reunion',''),messages:get('messages',[]).filter(x=>!cut||changedAfter(x,cut)),deletedMessages:get('deletedMessages',[]),answers:outAns,events:get('events',[]),spaceCards:cards.filter(x=>!cut||changedAfter(x,cut)),at:now}}
async function shortHash(bytes,n=8){let h=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));return [...h.slice(0,n)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function keyTag(raw){return shortHash(raw,6)}
async function encrypt(mode='delta'){let k=get('key','');if(!k)throw Error('Appairage requis');let raw=unb64u(k);if(raw.length!==32)throw Error('Clé locale invalide');let iv=crypto.getRandomValues(new Uint8Array(12)),key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt']),plain=new TextEncoder().encode(JSON.stringify(exportData(mode))),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,plain)),payload=new Uint8Array(iv.length+ct.length);payload.set(iv,0);payload.set(ct,iv.length);let token=b64u(payload),kt=await keyTag(raw),ph=await shortHash(payload,8);return `ND654.${kt}.${payload.length}.${ph}.${token}`}
async function parsePacket654(packet){let s=(packet||'').normalize('NFKC').replace(/[\s\u200B-\u200D\u2060\uFEFF]/g,'').trim();if(!s)throw Error('Paquet vide');let pos=s.indexOf('ND654.');if(pos<0)throw Error('Format ND654 invalide : le paquet complet ND654 est requis');s=s.slice(pos);let m=s.match(/^ND654\.([A-Fa-f0-9]{12})\.(\d+)\.([A-Fa-f0-9]{16})\.([A-Za-z0-9_-]+)/);if(!m)throw Error('Format ND654 invalide ou incomplet');return {keyTag:m[1].toUpperCase(),expectedLen:Number(m[2]),payloadHash:m[3].toUpperCase(),token:m[4]}}
async function decrypt(packet){let q=await parsePacket654(packet),blob=unb64u(q.token);if(blob.length!==q.expectedLen)throw Error(`Paquet tronqué/modifié : ${blob.length} octets reçus au lieu de ${q.expectedLen}`);let gotHash=await shortHash(blob,8);if(gotHash!==q.payloadHash)throw Error('Paquet modifié pendant le transport : empreinte du contenu différente');let stored=get('key','');if(!stored)throw Error('Appairage requis sur cet appareil');let raw=unb64u(stored);if(raw.length!==32)throw Error('Clé locale invalide');let localTag=await keyTag(raw);if(localTag!==q.keyTag)throw Error(`Clés différentes : empreinte locale ${localTag}, paquet ${q.keyTag}`);if(blob.length<30)throw Error('Paquet ND654 trop court');let iv=blob.slice(0,12),ct=blob.slice(12),key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['decrypt']);try{let pt=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ct);return JSON.parse(new TextDecoder().decode(pt))}catch(e){throw Error('Paquet intact et clé identique, mais authentification AES-GCM impossible')}}
function dedupe(a,b){let m=new Map([...a,...b].map(x=>[x.id,x]));return [...m.values()]}
function mergeData(d){if(d.v!==6)throw Error('Version incompatible');let deleted=[...new Set([...get('deletedMessages',[]),...(d.deletedMessages||[])])];set('deletedMessages',deleted);set('messages',dedupe(get('messages',[]),d.messages||[]).filter(m=>!deleted.includes(m.id)));set('events',dedupe(get('events',[]),d.events||[]));set('spaceCards',dedupe(get('spaceCards',[]),d.spaceCards||[]));let a=get('answers',{});for(const [qid,users] of Object.entries(d.answers||{}))a[qid]={...(a[qid]||{}),...users};set('answers',a);if(d.reunion)set('reunion',d.reunion);set('partner',d.from||{});if(d.packetAt)set('lastReceivedPacketAt',d.packetAt);if(d.ackFor){let cur=get('peerAckAt','');if(!cur||d.ackFor>cur)set('peerAckAt',d.ackFor)}}

const FRAG_SIZE=1800;
function fragmentPacket(packet){
  if(!packet||!packet.startsWith('ND654.'))throw Error('Paquet ND654 invalide');
  let pid='P'+Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,6).toUpperCase();
  let chunks=[];for(let i=0;i<packet.length;i+=FRAG_SIZE)chunks.push(packet.slice(i,i+FRAG_SIZE));
  return chunks.map((c,i)=>`ND655F.${pid}.${i+1}.${chunks.length}.${c}`);
}
function parseFragment(text){
  let s=(text||'').normalize('NFKC').replace(/[\u200B-\u200D\u2060\uFEFF]/g,'').trim();
  let pos=s.indexOf('ND655F.');if(pos<0)return null;s=s.slice(pos);
  let m=s.match(/^ND655F\.([A-Z0-9]+)\.(\d+)\.(\d+)\.([\s\S]+)$/i);
  if(!m)throw Error('Fragment ND655 invalide');
  let no=Number(m[2]),total=Number(m[3]);if(no<1||total<1||no>total||total>100)throw Error('Numérotation du fragment invalide');
  return {pid:m[1],no,total,data:m[4].replace(/\s/g,'')};
}
function fragmentStore(){return get('syncFragments',{})}
function saveFragment(f){
  let all=fragmentStore(),box=all[f.pid]||{total:f.total,parts:{},at:new Date().toISOString()};
  if(box.total!==f.total)throw Error('Fragments incompatibles pour ce paquet');
  box.parts[f.no]=f.data;box.at=new Date().toISOString();all[f.pid]=box;set('syncFragments',all);
  let count=Object.keys(box.parts).length;
  return {count,total:box.total,complete:count===box.total,packet:count===box.total?Array.from({length:box.total},(_,i)=>box.parts[i+1]).join(''):''};
}
function clearFragment(pid){let all=fragmentStore();delete all[pid];set('syncFragments',all)}
function renderFragments(frags){
  let box=$('#fragments');if(!box)return;
  box.innerHTML=frags.map((f,i)=>`<div class=event><b>Fragment ${i+1}/${frags.length}</b><textarea class=fragout readonly>${esc(f)}</textarea><button type=button class=ghost data-frag-copy="${i}">Copier ce fragment</button> <button type=button class=ghost data-frag-share="${i}">Partager</button></div>`).join('');
  box.dataset.fragments=JSON.stringify(frags);
}
async function copyText(t){if(navigator.clipboard){await navigator.clipboard.writeText(t);return}throw Error('Presse-papiers indisponible')}
function sync(a){let partner=get('partner',{});a.innerHTML=`<h2>⇄ Synchronisation V6.5.5</h2><div class=card><h3>État</h3><p>Moi : <b>${esc(me().name||'à configurer')}</b><br>Partenaire connu : <b>${esc(partner.name||'pas encore')}</b></p><p class=muted>Les gros paquets sont automatiquement découpés en fragments ND655F. Chaque fragment peut être envoyé séparément par WhatsApp.</p><p id=cryptoDiag class=status>Diagnostic en attente…</p></div><div class=card><button type=button class=action data-sync-action="delta">Créer le paquet court</button> <button type=button class=ghost data-sync-action="full">Sync complète</button><textarea id=packet placeholder="Le paquet ND654 apparaîtra ici" readonly></textarea><p id=size class=status></p><p id=createDiag class=status></p><div id=fragments></div></div><div class=card><h3>Recevoir</h3><p class=muted>Colle un fragment ND655F puis valide. L’application le conserve jusqu’à réception de tous les fragments. Tu peux aussi coller directement un paquet ND654 complet.</p><textarea id=incoming placeholder="Coller ici un fragment ND655F…"></textarea><button type=button class=action data-sync-action="receive">Ajouter / vérifier / fusionner</button><p id=diag class=status></p></div>`;syncSelfTest()}async function syncSelfTest(){let d=$('#cryptoDiag');if(!d)return;try{if(!window.crypto||!crypto.getRandomValues||!crypto.subtle)throw Error('WebCrypto indisponible');let probe=crypto.getRandomValues(new Uint8Array(32)),key=await crypto.subtle.importKey('raw',probe,'AES-GCM',false,['encrypt','decrypt']),iv=crypto.getRandomValues(new Uint8Array(12)),pt=new TextEncoder().encode('ND655'),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,pt),back=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ct);if(new TextDecoder().decode(back)!=='ND655')throw Error('auto-test incohérent');d.textContent='✅ Chiffrement de cet appareil opérationnel.'}catch(e){d.textContent='❌ Chiffrement indisponible : '+(e.message||e)}}
async function makePacketUI(mode){let d=$('#createDiag'),out=$('#packet'),size=$('#size');if(!d||!out)return;d.textContent='⏳ Création en cours…';if(size)size.textContent='';try{if(!window.crypto||!crypto.subtle)throw Error('WebCrypto indisponible sur cet appareil');let x=await encrypt(mode),frags=fragmentPacket(x);out.value=x;if(size)size.textContent=`${x.length} caractères • ${frags.length} fragment${frags.length>1?'s':''} • ${mode==='delta'?'paquet court':'synchronisation complète'}`;d.textContent=frags.length===1?'✅ Paquet créé : envoie le fragment ci-dessous.':`✅ Paquet créé et découpé en ${frags.length} fragments. Envoie-les tous dans l’ordre.`;renderFragments(frags)}catch(e){d.textContent='❌ Création impossible : '+(e.message||String(e));}}async function handleSyncAction(action,source=null){let d=$('#createDiag');if(action==='delta'||action==='full')return makePacketUI(action);if(action==='fragcopy'||action==='fragshare'){let box=$('#fragments'),frags=[];try{frags=JSON.parse(box?.dataset.fragments||'[]')}catch{}let i=Number(source?.dataset.fragCopy??source?.dataset.fragShare),t=frags[i];if(!t)return;if(action==='fragcopy'){try{await copyText(t);if(d)d.textContent=`✅ Fragment ${i+1}/${frags.length} copié.`}catch(e){if(d)d.textContent='❌ Copie impossible : '+(e.message||e)}}else{try{if(navigator.share)await navigator.share({title:`Nous Deux — fragment ${i+1}/${frags.length}`,text:t});else{await copyText(t);if(d)d.textContent='✅ Fragment copié : colle-le dans WhatsApp.'}}catch(e){if(e.name!=='AbortError'&&d)d.textContent='❌ Partage impossible : '+(e.message||e)}}return}
if(action==='receive'){let diag=$('#diag'),input=$('#incoming');if(!diag||!input)return;diag.textContent='⏳ Vérification en cours…';try{let raw=input.value||'',f=parseFragment(raw),packet=raw;if(f){let r=saveFragment(f);if(!r.complete){diag.textContent=`✅ Fragment ${f.no}/${f.total} reçu. ${r.count}/${r.total} fragments disponibles. Colle maintenant le suivant.`;input.value='';return}packet=r.packet;diag.textContent=`⏳ ${r.total}/${r.total} fragments reçus. Vérification du paquet complet…`;clearFragment(f.pid)}let x=await decrypt(packet);mergeData(x);diag.textContent=`✅ Paquet ${x.mode==='full'?'complet':'court'} valide reçu de ${x.from?.name||'partenaire'} — données fusionnées.`;input.value='';toast('Synchronisation réussie')}catch(e){diag.textContent='❌ '+(e.message||e)}}}
document.addEventListener('click',e=>{let b=e.target.closest('[data-sync-action],[data-frag-copy],[data-frag-share]');if(!b)return;e.preventDefault();if(b.dataset.fragCopy!==undefined)return handleSyncAction('fragcopy',b);if(b.dataset.fragShare!==undefined)return handleSyncAction('fragshare',b);handleSyncAction(b.dataset.syncAction,b)});
migrateBrokenAnswers();
$('#lock').onclick=()=>{view='pair';render()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();setInterval(()=>{if(view==='home'){let e=document.querySelector('.count');if(e)e.textContent=countdown()}},30000);