const D=window.ND6_DATA, $=s=>document.querySelector(s), esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const K='nd6.'; const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(K+k))??d}catch{return d}}, set=(k,v)=>localStorage.setItem(K+k,JSON.stringify(v));
let view='home', calCursor=new Date(); const me=()=>get('profile',{id:'',name:''});
function toast(x){let e=document.createElement('div');e.className='toast';e.textContent=x;document.body.append(e);setTimeout(()=>e.remove(),1800)}
function uuid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()}
function ensureProfile(){let p=me(); if(!p.id){p={id:uuid(),name:''};set('profile',p)} return p}
function fmt(dt){return new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(dt))}

function opts(from,to,val,pad=true){let h='';for(let i=from;i<=to;i++){let v=pad?String(i).padStart(2,'0'):String(i);h+=`<option value="${v}" ${String(val)===v?'selected':''}>${v}</option>`}return h}
function dateParts(value,withTime=false){let d=value?new Date(value):new Date(), y=d.getFullYear(),mo=String(d.getMonth()+1).padStart(2,'0'),da=String(d.getDate()).padStart(2,'0'),h=String(d.getHours()).padStart(2,'0'),mi=String(d.getMinutes()).padStart(2,'0');return {y:String(y),mo,da,h,mi}}
function dateSelectors(prefix,value,withTime=false){let x=dateParts(value,withTime),years=opts(new Date().getFullYear()-1,new Date().getFullYear()+10,x.y,false);return `<div class="datepick"><select id="${prefix}d" aria-label="Jour">${opts(1,31,x.da)}</select><select id="${prefix}m" aria-label="Mois">${opts(1,12,x.mo)}</select><select id="${prefix}y" aria-label="Année">${years}</select>${withTime?`<select id="${prefix}h" aria-label="Heure">${opts(0,23,x.h)}</select><span>:</span><select id="${prefix}i" aria-label="Minute">${opts(0,59,x.mi)}</select>`:''}</div>`}
function readDate(prefix,withTime=false){let y=$('#'+prefix+'y').value,m=$('#'+prefix+'m').value,d=$('#'+prefix+'d').value;let max=new Date(Number(y),Number(m),0).getDate();if(Number(d)>max)d=String(max).padStart(2,'0');return `${y}-${m}-${d}`+(withTime?`T${$('#'+prefix+'h').value}:${$('#'+prefix+'i').value}`:'')}
function countdown(){let x=get('reunion','');if(!x)return 'Date à définir';let ms=new Date(x)-Date.now();if(ms<=0)return '❤️ Vous êtes réunis';let d=Math.floor(ms/864e5);ms%=864e5;let h=Math.floor(ms/36e5);ms%=36e5;let m=Math.floor(ms/6e4);return `J-${d} • ${h} h • ${m} min`}
function render(){ensureProfile();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===view));let a=$('#app'); if(view==='home')home(a);if(view==='questions')qa(a,'questions');if(view==='challenges')qa(a,'challenges');if(view==='calendar')calendar(a);if(view==='sync')sync(a);if(view==='pair')pair(a);if(view==='spaces')spaces(a)}
function home(a){let p=me(),msgs=get('messages',[]),rv=get('reunion','');a.innerHTML=`<section class=hero><div>❤️</div><h1>Nous Deux</h1><p class=muted>${esc(p.name||'Configure ton prénom')}</p><div class=count>${countdown()}</div><p class=muted>avant vos retrouvailles</p></section><div class=card><h3>⏱️ Prochaines retrouvailles</h3><label>Jour / mois / année / heure / minute</label>${dateSelectors('r',rv,true)}<button class=action id=saveReunion>Enregistrer</button></div><div class=card><h3>💌 Messages</h3><textarea id=msg placeholder="Un petit mot pour l'autre…"></textarea><button class=action id=sendMsg>Ajouter au journal partagé</button>${msgs.slice(-5).reverse().map(m=>`<div class=event><b>${esc(m.authorName)}</b> <span class=status>${fmt(m.at)}</span><br>${esc(m.text)} <button class=ghost data-delmsg="${m.id}">Supprimer</button></div>`).join('')}</div><div class=grid><button class="ghost spacebtn" id=openSpaces>🔒 Espaces à deux</button><button class="ghost spacebtn" onclick="view='calendar';render()">🗓️ Nos week-ends</button></div>`;$('#saveReunion').onclick=()=>{set('reunion',readDate('r',true));toast('Retrouvailles enregistrées');render()};$('#sendMsg').onclick=()=>{let t=$('#msg').value.trim();if(!t)return;let p=me(),x=get('messages',[]);x.push({id:uuid(),authorId:p.id,authorName:p.name||'Moi',text:t,at:new Date().toISOString()});set('messages',x);render()};a.querySelectorAll('[data-delmsg]').forEach(b=>b.onclick=()=>{let id=b.dataset.delmsg;set('messages',get('messages',[]).filter(m=>m.id!==id));let del=get('deletedMessages',[]);if(!del.includes(id))del.push(id);set('deletedMessages',del);toast('Message supprimé');render()});$('#openSpaces').onclick=()=>{view='spaces';render()}}
function qa(a,type){let list=D[type], title=type==='questions'?'Questions':'Défis', themes=[...new Set(list.map(x=>x.theme))], pref=get(type+'Theme','Tous');let adult=get('adult',false);let filtered=list.filter(x=>(pref==='Tous'||x.theme===pref)&&(type!=='challenges'||adult||x.theme!=='Coquin'));let idx=get(type+'Idx',0)%filtered.length,item=filtered[idx],ans=get('answers',{}),p=me(),mine=(ans[item.id]||{})[p.id]||'';let others=Object.entries(ans[item.id]||{}).filter(([id])=>id!==p.id);a.innerHTML=`<h2>${type==='questions'?'❓':'✨'} ${title}</h2><div class=tabs>${['Tous',...themes.filter(t=>adult||t!=='Coquin')].map(t=>`<button class="${t===pref?'btn':'ghost'}" data-theme="${esc(t)}">${esc(t)}</button>`).join('')}</div>${type==='challenges'?`<div class=card><label><input id=adult type=checkbox ${adult?'checked':''} style="width:auto"> Activer la catégorie « Coquin » (suggestive, optionnelle)</label></div>`:''}<div class=card><span class=pill>${esc(item.theme)}</span><h3>${esc(item.text)}</h3><label>Ma réponse / mon retour</label><textarea id=ans>${esc(mine)}</textarea><button class=action id=saveAns>Enregistrer ma réponse</button><button class=ghost id=next style="margin-left:6px">Suivant</button></div><div class=card><h3>❤️ Réponses reçues</h3>${others.length?others.map(([id,r])=>`<div class=answer><b>${esc(r.name||'Partenaire')}</b><p>${esc(r.text||r)}</p></div>`).join(''):'<p class=muted>En attente de la réponse de ton/ta partenaire.</p>'}</div><p class=muted>${idx+1} / ${filtered.length} dans cette sélection • ${list.length} ${title.toLowerCase()} au total</p>`;a.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{set(type+'Theme',b.dataset.theme);set(type+'Idx',0);render()});if($('#adult'))$('#adult').onchange=e=>{set('adult',e.target.checked);render()};$('#saveAns').onclick=()=>{let all=get('answers',{});all[item.id]=all[item.id]||{};all[item.id][p.id]={name:p.name||'Moi',text:$('#ans').value,at:new Date().toISOString()};set('answers',all);toast('Réponse enregistrée')};$('#next').onclick=()=>{set(type+'Idx',idx+1);render()}}
function calendar(a){let y=calCursor.getFullYear(),m=calCursor.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()+1),events=get('events',[]),days=[];for(let i=0;i<42;i++){let d=new Date(start);d.setDate(start.getDate()+i);let iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`, has=events.some(e=>iso>=e.start&&iso<=e.end);days.push(`<div class="day ${d.getMonth()!==m?'off':''} ${iso===new Date().toISOString().slice(0,10)?'today':''} ${has?'has':''}" data-date="${iso}">${d.getDate()}</div>`)}a.innerHTML=`<div class=calendar-head><button class=ghost id=prev>‹</button><h2>${new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(first)}</h2><button class=ghost id=nextm>›</button></div><div class=cal>${['L','M','M','J','V','S','D'].map(x=>`<div class=dow>${x}</div>`).join('')}${days.join('')}</div><div class=card><h3>➕ Date / week-end</h3><input id=et placeholder="Titre"><label>Du</label>${dateSelectors('s','',false)}<label>Au</label>${dateSelectors('e','',false)}<textarea id=en placeholder="Note (facultatif)"></textarea><button class=action id=addEvent>Ajouter</button></div><div class=card><h3>Événements</h3>${events.slice().sort((x,y)=>x.start.localeCompare(y.start)).map(e=>`<div class=event><b>${esc(e.title)}</b><br><span class=status>${e.start}${e.end!==e.start?' → '+e.end:''}</span><br>${esc(e.note||'')} <button class=ghost data-del="${e.id}">Supprimer</button></div>`).join('')||'<p class=muted>Aucun événement.</p>'}</div>`;$('#prev').onclick=()=>{calCursor=new Date(y,m-1,1);render()};$('#nextm').onclick=()=>{calCursor=new Date(y,m+1,1);render()};a.querySelectorAll('.day[data-date]').forEach(el=>el.onclick=()=>{let z=el.dataset.date.split('-');['s','e'].forEach(p=>{$('#'+p+'y').value=z[0];$('#'+p+'m').value=z[1];$('#'+p+'d').value=z[2]});toast('Date sélectionnée : '+z.reverse().join('/'))});$('#addEvent').onclick=()=>{let s=readDate('s'),e=readDate('e'),t=$('#et').value.trim();if(!t)return toast('Titre requis');if(e<s)return toast('La date de fin doit être après le début');let x=get('events',[]);x.push({id:uuid(),title:t,start:s,end:e,note:$('#en').value,authorId:me().id});set('events',x);render()};a.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{set('events',get('events',[]).filter(e=>e.id!==b.dataset.del));render()})}
function spaces(a){let cards=get('spaceCards',[]);a.innerHTML=`<h2>🔒 Espaces à deux</h2><p class=muted>Crée une note secrète, prépare-la à envoyer, ou partage-la avec ton/ta partenaire.</p>${Object.entries(D.spaces).map(([s,rs])=>`<div class=card><h3>${esc(s)}</h3>${rs.map(r=>`<button class="ghost spacebtn" data-r="${esc(s+' • '+r)}">${esc(r)}</button>`).join('')}</div>`).join('')}<div class=card><h3>Contenus</h3>${cards.slice().reverse().map(c=>`<div class=event><span class=pill>${c.state==='secret'?'🔒 Secret':c.state==='send'?'💌 À envoyer':'❤️ Commun'}</span><b>${esc(c.rubric)}</b><p>${esc(c.text)}</p><small>${esc(c.authorName)}</small></div>`).join('')||'<p class=muted>Aucun contenu.</p>'}</div>`;a.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{let text=prompt(b.dataset.r+'\n\nTon contenu :');if(!text)return;let st=prompt('État : secret / send / shared','send');if(!['secret','send','shared'].includes(st))st='send';let p=me(),x=get('spaceCards',[]);x.push({id:uuid(),rubric:b.dataset.r,text,state:st,authorId:p.id,authorName:p.name||'Moi',at:new Date().toISOString()});set('spaceCards',x);render()})}
function b64u(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64u(s){
  s=(s||'').normalize('NFKC').replace(/[\s\u200B-\u200D\u2060\uFEFF]/g,'').replace(/[^A-Za-z0-9_-]/g,'');
  s=s.replace(/-/g,'+').replace(/_/g,'/');
  while(s.length%4)s+='=';
  try{let x=atob(s);return Uint8Array.from(x,c=>c.charCodeAt(0))}
  catch(e){throw Error('Décodage Base64URL impossible sur cet appareil')}
}
async function fp(raw){let h=new Uint8Array(await crypto.subtle.digest('SHA-256',raw));return [...h.slice(0,12)].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase().match(/.{1,4}/g).join(' · ')}
async function pair(a){let key=get('key',''),p=me();a.innerHTML=`<h2>🔐 Appairage V6</h2><div class=card><label>Ton prénom / pseudo sur cet appareil</label><input id=name value="${esc(p.name)}"><button class=action id=saveName>Enregistrer</button></div><div class=card><h3>Clé du couple</h3><p class=muted>Une même clé sur vos deux téléphones, deux identités d'appareil distinctes.</p><textarea id=key placeholder="Clé Base64URL">${esc(key)}</textarea><button class=action id=createKey>Créer une clé</button> <button class=ghost id=importKey>Importer</button><p id=fingerprint class=status></p></div>`;$('#saveName').onclick=()=>{p.name=$('#name').value.trim();set('profile',p);toast('Profil enregistré')};$('#createKey').onclick=async()=>{let raw=crypto.getRandomValues(new Uint8Array(32)),k=b64u(raw);set('key',k);$('#key').value=k;$('#fingerprint').textContent='Empreinte : '+await fp(raw)};$('#importKey').onclick=async()=>{try{let raw=unb64u($('#key').value.trim());if(raw.length!==32)throw 0;set('key',b64u(raw));$('#fingerprint').textContent='Empreinte : '+await fp(raw);toast('Clé importée')}catch{toast('Clé invalide')}};if(key){try{$('#fingerprint').textContent='Empreinte : '+await fp(unb64u(key))}catch{}}}
function exportData(){let p=me(),cards=get('spaceCards',[]).filter(c=>c.state!=='secret');return {v:6,from:{id:p.id,name:p.name},reunion:get('reunion',''),messages:get('messages',[]),deletedMessages:get('deletedMessages',[]),answers:get('answers',{}),events:get('events',[]),spaceCards:cards,at:new Date().toISOString()}}
async function encrypt(){let k=get('key','');if(!k)throw Error('Appairage requis');let raw=unb64u(k),iv=crypto.getRandomValues(new Uint8Array(12)),key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['encrypt']),pt=new TextEncoder().encode(JSON.stringify(exportData())),ct=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},key,pt));return 'NOUS-DEUX-ND6.'+b64u(iv)+'.'+b64u(ct)}
function dedupe(a,b){let m=new Map([...a,...b].map(x=>[x.id,x]));return [...m.values()]}
async function decrypt(packet){
  let s=(packet||'').normalize('NFKC').replace(/[\s\u200B-\u200D\u2060\uFEFF]/g,'');
  let pos=s.indexOf('NOUS-DEUX-ND6.'); if(pos<0)throw Error('Format ND6 invalide : en-tête absent');
  s=s.slice(pos); let m=s.match(/^NOUS-DEUX-ND6\.([A-Za-z0-9_-]+)\.([A-Za-z0-9_-]+)/);
  if(!m)throw Error('Format ND6 invalide : paquet incomplet ou modifié');
  let ivs=m[1],cts=m[2],stored=get('key',''); if(!stored)throw Error('Appairage requis sur cet appareil');
  let raw=unb64u(stored); if(raw.length!==32)throw Error('Clé locale invalide');
  let iv=unb64u(ivs),ct=unb64u(cts); if(iv.length!==12||ct.length<17)throw Error('Format ND6 invalide : données tronquées');
  let key=await crypto.subtle.importKey('raw',raw,'AES-GCM',false,['decrypt']);
  try{let pt=await crypto.subtle.decrypt({name:'AES-GCM',iv},key,ct);return JSON.parse(new TextDecoder().decode(pt))}
  catch(e){throw Error('Authentification ND6 impossible : paquet altéré/tronqué ou clé différente')}
}
function mergeData(d){if(d.v!==6)throw Error('Version incompatible');let deleted=[...new Set([...get('deletedMessages',[]),...(d.deletedMessages||[])])];set('deletedMessages',deleted);set('messages',dedupe(get('messages',[]),d.messages||[]).filter(m=>!deleted.includes(m.id)));set('events',dedupe(get('events',[]),d.events||[]));set('spaceCards',dedupe(get('spaceCards',[]),d.spaceCards||[]));let a=get('answers',{});for(const [qid,users] of Object.entries(d.answers||{}))a[qid]={...(a[qid]||{}),...users};set('answers',a);if(d.reunion)set('reunion',d.reunion);set('partner',d.from||{});}
function sync(a){let partner=get('partner',{});a.innerHTML=`<h2>⇄ Synchronisation ND6</h2><div class=card><h3>État</h3><p>Moi : <b>${esc(me().name||'à configurer')}</b><br>Partenaire connu : <b>${esc(partner.name||'pas encore')}</b></p><p class=muted>AES-256-GCM + Base64URL. Les espaces marqués 🔒 Secret ne quittent jamais cet appareil.</p></div><div class=card><button class=action id=make>Créer le paquet chiffré</button><textarea id=packet placeholder="Le paquet ND6 apparaîtra ici"></textarea><button class=ghost id=share>Partager (WhatsApp…)</button> <button class=ghost id=copy>Copier</button></div><div class=card><h3>Recevoir</h3><textarea id=incoming placeholder="Coller ici le paquet NOUS-DEUX-ND6…"></textarea><button class=action id=receive>Vérifier, déchiffrer et fusionner</button><p id=diag class=status></p></div>`;$('#make').onclick=async()=>{try{$('#packet').value=await encrypt();$('#diag').textContent='Paquet créé et authentifié.'}catch(e){toast(e.message)}};$('#copy').onclick=async()=>{await navigator.clipboard.writeText($('#packet').value);toast('Paquet copié')};$('#share').onclick=async()=>{let t=$('#packet').value;if(!t)return toast('Crée d’abord le paquet');if(navigator.share)await navigator.share({title:'Nous Deux V6',text:t});else{await navigator.clipboard.writeText(t);toast('Copié : colle-le dans WhatsApp')}};$('#receive').onclick=async()=>{try{let d=await decrypt($('#incoming').value);mergeData(d);$('#diag').textContent=`✅ Paquet valide reçu de ${d.from?.name||'partenaire'} — données fusionnées sans écraser les réponses individuelles.`;toast('Synchronisation réussie')}catch(e){$('#diag').textContent='❌ '+(e.message)}}}
$('#lock').onclick=()=>{view='pair';render()};document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.v;render()});if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');render();setInterval(()=>{if(view==='home'){let e=document.querySelector('.count');if(e)e.textContent=countdown()}},30000);